// Dual-format presets: templates serving two wire shapes.
package templates

import (
	"github.com/jonaskahn/relo/internal/catalog"
)

var dualFormatTemplates = []Template{
	{
		ID:                  "deepseek",
		Label:               "DeepSeek",
		Kind:                KindKey,
		Origin:              catalog.OriginTemplate,
		Auth:                catalog.AuthAPIKey,
		KeyHeader:           catalog.KeyHeaderBearer,
		DefaultFormat:       catalog.FormatOpenAIChat,
		DefaultBaseURL:      "https://api.deepseek.com/v1",
		ModelsSource:        "listing",
		ModelsFormat:        catalog.ModelsOpenAI,
		ModelsDevProviderID: "deepseek",
		DocURL:              "https://api-docs.deepseek.com",
		KeyEnv:              []string{"DEEPSEEK_API_KEY"},
		AvailableFormats: []FormatOption{
			{
				Format:         catalog.FormatOpenAIChat,
				DefaultBaseURL: "https://api.deepseek.com/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Chat Completions",
			},
			{
				Format:         catalog.FormatAnthropic,
				DefaultBaseURL: "https://api.deepseek.com/anthropic/v1",
				KeyHeader:      catalog.KeyHeaderXApiKey,
				ModelsFormat:   catalog.ModelsAnthropic,
				Label:          "Anthropic Messages API",
			},
		},
	},
	{
		ID:                  "minimax",
		Label:               "MiniMax",
		Kind:                KindKey,
		Origin:              catalog.OriginTemplate,
		Auth:                catalog.AuthAPIKey,
		KeyHeader:           catalog.KeyHeaderBearer,
		DefaultFormat:       catalog.FormatOpenAIChat,
		DefaultBaseURL:      "https://api.minimax.io/v1",
		ModelsSource:        "listing",
		ModelsFormat:        catalog.ModelsOpenAI,
		ModelsDevProviderID: "minimax",
		KeyEnv:              []string{"MINIMAX_API_KEY"},
		AvailableFormats: []FormatOption{
			{
				Format:         catalog.FormatOpenAIChat,
				DefaultBaseURL: "https://api.minimax.io/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Chat Completions",
			},
			{
				Format:         catalog.FormatAnthropic,
				DefaultBaseURL: "https://api.minimax.io/anthropic/v1",
				KeyHeader:      catalog.KeyHeaderXApiKey,
				ModelsFormat:   catalog.ModelsAnthropic,
				Label:          "Anthropic Messages API",
			},
		},
	},
	{
		ID:                  "minimax-cn",
		Label:               "MiniMax (China)",
		Kind:                KindKey,
		Origin:              catalog.OriginTemplate,
		Auth:                catalog.AuthAPIKey,
		KeyHeader:           catalog.KeyHeaderBearer,
		DefaultFormat:       catalog.FormatOpenAIChat,
		DefaultBaseURL:      "https://api.minimaxi.com/v1",
		ModelsSource:        "listing",
		ModelsFormat:        catalog.ModelsOpenAI,
		ModelsDevProviderID: "minimax-cn",
		KeyEnv:              []string{"MINIMAX_API_KEY"},
		AvailableFormats: []FormatOption{
			{
				Format:         catalog.FormatOpenAIChat,
				DefaultBaseURL: "https://api.minimaxi.com/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Chat Completions",
			},
			{
				Format:         catalog.FormatAnthropic,
				DefaultBaseURL: "https://api.minimaxi.com/anthropic/v1",
				KeyHeader:      catalog.KeyHeaderXApiKey,
				ModelsFormat:   catalog.ModelsAnthropic,
				Label:          "Anthropic Messages API",
			},
		},
	},
	{
		ID:                  "alibaba",
		Label:               "Alibaba DashScope / Qwen",
		Kind:                KindKey,
		Origin:              catalog.OriginTemplate,
		Auth:                catalog.AuthAPIKey,
		KeyHeader:           catalog.KeyHeaderBearer,
		DefaultFormat:       catalog.FormatOpenAIChat,
		DefaultBaseURL:      "https://dashscope.aliyuncs.com/compatible-mode/v1",
		ModelsSource:        "listing",
		ModelsFormat:        catalog.ModelsOpenAI,
		ModelsDevProviderID: "alibaba",
		KeyEnv:              []string{"DASHSCOPE_API_KEY"},
		AvailableFormats: []FormatOption{
			{
				Format:         catalog.FormatOpenAIChat,
				DefaultBaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Chat Completions",
			},
			{
				Format:         catalog.FormatAnthropic,
				DefaultBaseURL: "https://dashscope.aliyuncs.com/apps/anthropic/v1",
				KeyHeader:      catalog.KeyHeaderXApiKey,
				ModelsFormat:   catalog.ModelsAnthropic,
				Label:          "Anthropic Messages API",
			},
		},
	},
	{
		ID:             "teamorouter",
		Label:          "TeamoRouter",
		Kind:           KindKey,
		Origin:         catalog.OriginTemplate,
		Auth:           catalog.AuthAPIKey,
		KeyHeader:      catalog.KeyHeaderBearer,
		DefaultFormat:  catalog.FormatOpenAIChat,
		DefaultBaseURL: "https://api.teamorouter.cn/v1",
		ModelsSource:   "listing",
		ModelsFormat:   catalog.ModelsOpenAI,
		DocURL:         "https://teamorouter.cn/docs",
		AvailableFormats: []FormatOption{
			{
				Format:         catalog.FormatOpenAIChat,
				DefaultBaseURL: "https://api.teamorouter.cn/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Chat Completions",
			},
			{
				Format:         catalog.FormatOpenAIResp,
				DefaultBaseURL: "https://api.teamorouter.cn/v1",
				KeyHeader:      catalog.KeyHeaderBearer,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "OpenAI Responses API",
			},
			{
				Format:         catalog.FormatAnthropic,
				DefaultBaseURL: "https://api.teamorouter.cn/v1",
				KeyHeader:      catalog.KeyHeaderXApiKey,
				ModelsFormat:   catalog.ModelsOpenAI,
				Label:          "Anthropic Messages API",
			},
		},
	},
}

var localPresets = []Template{
	{
		ID:             "ollama",
		Label:          "Ollama",
		Kind:           KindLocal,
		Origin:         catalog.OriginCustom,
		Auth:           catalog.AuthNone,
		KeyHeader:      catalog.KeyHeaderNone,
		DefaultFormat:  catalog.FormatOpenAIChat,
		DefaultBaseURL: "http://localhost:11434/v1",
		ModelsSource:   "listing",
		ModelsFormat:   catalog.ModelsOpenAI,
	},
	{
		ID:             "vllm",
		Label:          "vLLM",
		Kind:           KindLocal,
		Origin:         catalog.OriginCustom,
		Auth:           catalog.AuthNone,
		KeyHeader:      catalog.KeyHeaderNone,
		DefaultFormat:  catalog.FormatOpenAIChat,
		DefaultBaseURL: "http://localhost:8000/v1",
		ModelsSource:   "listing",
		ModelsFormat:   catalog.ModelsOpenAI,
	},
	{
		ID:             "lm-studio",
		Label:          "LM Studio",
		Kind:           KindLocal,
		Origin:         catalog.OriginCustom,
		Auth:           catalog.AuthNone,
		KeyHeader:      catalog.KeyHeaderNone,
		DefaultFormat:  catalog.FormatOpenAIChat,
		DefaultBaseURL: "http://localhost:1234/v1",
		ModelsSource:   "listing",
		ModelsFormat:   catalog.ModelsOpenAI,
	},
	{
		ID:             "litellm",
		Label:          "LiteLLM",
		Kind:           KindLocal,
		Origin:         catalog.OriginCustom,
		Auth:           catalog.AuthAPIKey,
		KeyHeader:      catalog.KeyHeaderBearer,
		DefaultFormat:  catalog.FormatOpenAIChat,
		DefaultBaseURL: "http://localhost:4000/v1",
		ModelsSource:   "listing",
		ModelsFormat:   catalog.ModelsOpenAI,
	},
}
